//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BucksSafePlaceSite2.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Location
    {
        public int LocationID { get; set; }
        [System.ComponentModel.DataAnnotations.Required]
        public string BusinessName { get; set; }
        [System.ComponentModel.DataAnnotations.Required]
        public string BusinessAddress { get; set; }
        [System.ComponentModel.DataAnnotations.Required]
        public string Postcode { get; set; }
        [System.ComponentModel.DataAnnotations.Required]
        public string TelephoneNumber { get; set; }
    }
}
